site_name: Kometa Wiki
site_author: meisnate12
site_description: Kometa is an open-source python project allowing you to unlock the potential of your media server.
site_url: https://<slug>.kometa.wiki/en/latest/
repo_name: Kometa
repo_url: https://github.com/Kometa-Team/Kometa

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/favicon.png
  custom_dir: docs/overrides
  font:
    text: Open Sans
    code: Fira Code
  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  icon:
    alternate: material/file-document-multiple-outline
plugins:
  - glightbox
  - search:
      lang: en
  - open-in-new-tab
  - include-markdown
  - redirects:
      redirect_maps:
        'discord.md': 'https://kometa.wiki/en/nightly/link/'
        'redact.md': 'https://regex101.com/r/DMo1DQ/latest'
        'link.md': 'https://discord.com/invite/kometa-822460010649878528'
        'malauth.md': 'https://replit.com/@chazlarson/MALAuth'
        'traktauth.md': 'https://replit.com/@chazlarson/TraktAuth'
  - material-plausible
extra:
  alternate:
    - name: Latest Docs
      link: /en/latest/
      lang: en
    - name: Develop Docs
      link: /en/develop/
      lang: en
    - name: Nightly Docs
      link: /en/nightly/
      lang: en
  social:
    - icon: fontawesome/solid/heart
      class: md-social__link heart
      link: 'https://github.com/sponsors/meisnate12'
      name: Donate
    - icon: fontawesome/brands/discord
      class: md-social__link
      link: 'https://kometa.wiki/en/latest/discord/'
      name: Discord
    - icon: fontawesome/brands/github
      class: md-social__link
      link: 'https://github.com/Kometa-Team/Kometa'
      name: GitHub
  analytics:
    provider: plausible
    domain: kometa.wiki/en/latest
    src: "https://analytics.kometa.wiki/js/script.js"
copyright: Copyright &copy; 2024 meisnate12
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - neoteroi.cards
extra_css:
  - stylesheets/cards.css
  - stylesheets/extra.css
  - stylesheets/termynal.css
  - stylesheets/custom.css

extra_javascript:
  - stylesheets/termynal.js
  - stylesheets/custom.js
  - stylesheets/branch.js

nav:
  - KOMETA:
      - Home: index.md
      - INSTALLATION:
        - Installing Kometa: kometa/install/overview.md
        - Docker Images: kometa/install/images.md
        - Walkthroughs:
          - Local (Win/Mac/Linux): kometa/install/local.md
          - Docker: kometa/install/docker.md
          - unRAID: kometa/install/unraid.md
          - Kubernetes: kometa/install/kubernetes.md
          - QNAP: kometa/install/qnap.md
          - Synology: kometa/install/synology.md
      - POST-INSTALL:
        - Run Commands & Env Variables: kometa/environmental.md
        - YAML Files Explained: kometa/yaml.md
        - Log Files & Common Errors: kometa/logs.md
        - Frequently Asked Questions: kometa/faqs.md
        - Explanation Guides: &guides
          - Overview: kometa/guides/overview.md
          - Switching from PMM to Kometa: kometa/guides/rebrand.md
          - Plex Ratings Explained: kometa/guides/ratings.md
          - Kometa Sorting Guide: kometa/guides/order.md
          - Scheduling Kometa Runs Guide: kometa/guides/scheduling.md
          - Image Asset Directory Guide: kometa/guides/assets.md
          - Formula 1 Metadata Guide: kometa/guides/formula.md
          - MediUX Assets Guide: kometa/guides/mediux.md
        - Companion Scripts: &scripts
          - Overview: kometa/scripts/overview.md
          - ImageMaid: kometa/scripts/imagemaid.md
          - Kometa Overlay Reset: kometa/scripts/overlay-reset.md
      - USEFUL LINKS: &links
        - Feature Requests: https://features.kometa.wiki/
        - Bugs & Issues: https://github.com/Kometa-Team/Kometa/issues
        - Community Configs: https://github.com/Kometa-Team/Community-Configs
        - Discord Server: https://kometa.wiki/en/latest/discord/
        - Donate/Sponsor Kometa: https://github.com/sponsors/meisnate12
        - Acknowledgements: kometa/acknowledgements.md
  - CONFIGURATION FILE:
      - Overview: config/overview.md
      - STRUCTURE:
        - LIBRARIES:
          - Library Attributes: config/libraries.md
          - File Blocks: config/files.md
          - Library Operations: config/operations.md
        - PLAYLISTS:
          - Playlist Files: config/playlists.md
        - SETTINGS:
          - Settings: config/settings.md
        - WEBHOOKS:
          - Webhooks: config/webhooks.md
        - REQUIRED CONNECTIONS:
          - Plex: config/plex.md
          - TMDb: config/tmdb.md
        - OPTIONAL CONNECTIONS:
          - Tautulli: config/tautulli.md
          - Github: config/github.md
          - OMDb: config/omdb.md
          - MDBList: config/mdblist.md
          - Notifiarr: config/notifiarr.md
          - Gotify: config/gotify.md
          - AniDB: config/anidb.md
          - Radarr: config/radarr.md
          - Sonarr: config/sonarr.md
          - Trakt: config/trakt.md
          - MyAnimeList: config/myanimelist.md
          - Trakt and MyAnimeList Authentication: config/authentication.md
      - OTHER:
        - Scheduling Parts: config/schedule.md
  - KOMETA DEFAULTS:
      - Defaults Usage Guide: defaults/guide.md
      - Defaults Files: defaults/files.md
      - COLLECTIONS DEFAULTS:
        - Collections: defaults/collections.md
        - Shared Variables: defaults/collection_variables.md
        - Separators: defaults/separators.md
        - Award:
          - Separator: defaults/award/separator.md
          - Academy Awards (Oscars): defaults/award/oscars.md
          - Berlin Film Festival Awards: defaults/award/berlinale.md
          - British Academy of Film Awards: defaults/award/bafta.md
          - Cannes Film Festival Awards: defaults/award/cannes.md
          - CÃ©sar Awards: defaults/award/cesar.md
          - Critics Choice Awards: defaults/award/choice.md
          - Emmy Awards: defaults/award/emmy.md
          - Golden Globe Awards: defaults/award/golden.md
          - Independent Spirit Awards: defaults/award/spirit.md
          - National Film Registry: defaults/award/nfr.md
          - People's Choice Awards: defaults/award/pca.md
          - Razzie Awards: defaults/award/razzie.md
          - Sundance Film Festival Awards: defaults/award/sundance.md
          - Toronto International Film Festival: defaults/award/tiff.md
          - Venice Film Festival Awards: defaults/award/venice.md
        - Chart:
          - Separator: defaults/chart/separator.md
          - Basic Charts: defaults/chart/basic.md
          - AniList Charts: defaults/chart/anilist.md
          - IMDb Charts: defaults/chart/imdb.md
          - Letterboxd Charts: defaults/chart/letterboxd.md
          - MyAnimeList Charts: defaults/chart/myanimelist.md
          - Tautulli Charts: defaults/chart/tautulli.md
          - TMDb Charts: defaults/chart/tmdb.md
          - Trakt Charts: defaults/chart/trakt.md
          - Other Charts: defaults/chart/other.md
        - Content:
          - Genres: defaults/both/genre.md
          - Franchises (Movie): defaults/movie/franchise.md
          - Franchises (Show): defaults/show/franchise.md
          - Universes: defaults/both/universe.md
          - Based On...: defaults/both/based.md
          - Collectionless: defaults/both/collectionless.md
        - Content Rating:
          - US Content Ratings (Movie): defaults/movie/content_rating_us.md
          - US Content Ratings (Show): defaults/show/content_rating_us.md
          - UK Content Ratings: defaults/both/content_rating_uk.md
          - DE Content Ratings: defaults/both/content_rating_de.md
          - AU Content Ratings: defaults/both/content_rating_au.md
          - NZ Content Ratings: defaults/both/content_rating_nz.md
          - MyAnimeList Content Ratings: defaults/both/content_rating_mal.md
          - Common Sense Media Content Ratings: defaults/both/content_rating_cs.md
        - Location:
          - Countries (Movie): defaults/movie/country.md
          - Countries (Show): defaults/show/country.md
          - Regions (Movie): defaults/movie/region.md
          - Regions (Show): defaults/show/region.md
          - Continents (Movie): defaults/movie/continent.md
          - Continents (Show): defaults/show/continent.md
        - Media:
          - Aspect Ratio: defaults/both/aspect.md
          - Resolutions: defaults/both/resolution.md
          - Audio Languages: defaults/both/audio_language.md
          - Subtitle Languages: defaults/both/subtitle_language.md
        - Production:
          - Networks: defaults/show/network.md
          - Streaming: defaults/both/streaming.md
          - Studios: defaults/both/studio.md
        - People:
          - Actors: defaults/both/actor.md
          - Directors: defaults/movie/director.md
          - Producers: defaults/movie/producer.md
          - Writers: defaults/movie/writer.md
        - Time:
          - Seasonal: defaults/movie/seasonal.md
          - Years: defaults/both/year.md
          - Decades (Movie): defaults/movie/decade.md
          - Decades (Show): defaults/show/decade.md
      - PLAYLIST DEFAULTS:
        - Playlists: defaults/playlist.md
      - OVERLAY DEFAULTS:
        - Overlays: defaults/overlays.md
        - Shared Variables: defaults/overlay_variables.md
        - Chart:
          - Ribbon: defaults/overlays/ribbon.md
        - Content:
          - Episode Info: defaults/overlays/episode_info.md
          - MediaStinger: defaults/overlays/mediastinger.md
          - Ratings: defaults/overlays/ratings.md
          - Status: defaults/overlays/status.md
        - Content Rating:
          - US Content Ratings (Movie): defaults/overlays/content_rating_us_movie.md
          - US Content Ratings (Show): defaults/overlays/content_rating_us_show.md
          - UK Content Ratings: defaults/overlays/content_rating_uk.md
          - DE Content Ratings: defaults/overlays/content_rating_de.md
          - AU Content Ratings: defaults/overlays/content_rating_au.md
          - NZ Content Ratings: defaults/overlays/content_rating_nz.md
          - Common Sense Age Ratings: defaults/overlays/commonsense.md
        - Media:
          - Aspect Ratio: defaults/overlays/aspect.md
          - Audio Codec: defaults/overlays/audio_codec.md
          - Audio/Subtitle Language Count: defaults/overlays/language_count.md
          - Audio/Subtitle Language Flags: defaults/overlays/languages.md
          - Resolution/Edition: defaults/overlays/resolution.md
          - Runtimes: defaults/overlays/runtimes.md
          - Versions: defaults/overlays/versions.md
          - Video Format: defaults/overlays/video_format.md
        - Production:
          - Networks: defaults/overlays/network.md
          - Streaming: defaults/overlays/streaming.md
          - Studios: defaults/overlays/studio.md
        - Utility:
          - Direct Play Only: defaults/overlays/direct_play.md
  - FILES & BUILDERS:
      - Overview: files/overview.md
      - FILES:
        - Collection Files: files/collections.md
        - Overlay Files: files/overlays.md
        - Playlist Files: files/playlists.md
        - Metadata Files: files/metadata.md
        - Definition Templates: files/templates.md
        - Dynamic Collections: files/dynamic.md
        - Dynamic Collection Types & Data: files/dynamic_types.md
      - DEFINITION ATTRIBUTES:
        - Builders:
          - Overview: files/builders/overview.md
          - Dumb Plex Builders: files/builders/plex.md
          - Smart Plex Builders: files/builders/smart.md
          - TMDb Builders: files/builders/tmdb.md
          - TVDb Builders: files/builders/tvdb.md
          - IMDb Builders: files/builders/imdb.md
          - Trakt Builders: files/builders/trakt.md
          - Tautulli Builders: files/builders/tautulli.md
          - Radarr Builders: files/builders/radarr.md
          - Sonarr Builders: files/builders/sonarr.md
          - MDBList Builders: files/builders/mdblist.md
          - Letterboxd Builders: files/builders/letterboxd.md
          - ICheckMovies Builders: files/builders/icheckmovies.md
          - BoxOfficeMojo Builders: files/builders/mojo.md
          - Reciperr Builders: files/builders/reciperr.md
          - StevenLu Builders: files/builders/stevenlu.md
          - AniDB Builders: files/builders/anidb.md
          - AniList Builders: files/builders/anilist.md
          - MyAnimeList Builders: files/builders/myanimelist.md
        - Filters: files/filters.md
        - Definition Settings: files/settings.md
        - Radarr/Sonarr Settings: files/arr.md
        - Collection/Playlist Metadata Updates: files/updates.md
        - Item Metadata Updates: files/item_updates.md
  - MISCELLANEOUS:
    - EXPLANATION GUIDES: *guides
    - COMPANION SCRIPTS: *scripts
    - USEFUL LINKS: *links
  - SPONSOR: https://github.com/sponsors/meisnate12
#  - SHOWCASE:
#    - Overlays Showcase: showcase/overlays.md
