##############################################################################
#                       FlixPatrol Charts Collections                        #
#                 Created by Yozora, Bullmoose20, anon_fawkes & Sohjiro      #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#     https://metamanager.wiki/en/latest/defaults/chart/flixpatrol.html      #
##############################################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "01"
    pre: "_#"
    image: chart/<<collection_name_encoded>>

translations:
  pmm: translations

templates:
  flixpatrol:
    default:
      location: world
      location_<<key>>: <<location>>
      time_window: last_week
      time_window_<<key>>: <<time_window>>
      limit: 10
      limit_<<key>>: <<limit>>
    flixpatrol_top:
      platform: <<platform>>
      location: <<location_<<key>>>>
      time_window: <<time_window_<<key>>>>
      limit: <<limit_<<key>>>>

dynamic_collections:
  FlixPatrol:
    type: custom
    data:
      netflix: Netflix
      disney: Disney+
      hbo: HBO
      hulu: Hulu
      paramount: Paramount+
      prime: Prime Video
    title_format: <<key_name>> Top <<limit>>
    template:
      - flixpatrol
      - translation
      - shared
      - arr
      - custom
    template_variables:
      limit:
        default: 10
      platform:
        default: <<key>>
        paramount: paramount_plus
        prime: amazon_prime
      image:
        default: chart/<<key>>_top
      translation_key:
        default: flixpatrol
