##############################################################################
#                          IMDb Charts Collections                           #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#        https://metamanager.wiki/en/latest/defaults/chart/imdb.html         #
##############################################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "020"
    image: chart/<<mapping_name_encoded>>

templates:
  imdb_chart:
    imdb_chart: <<chart>>_<<library_type>>s

collections:
  IMDb Popular:
    variables:
      key: popular
    template:
      - name: imdb_chart
        chart: popular
      - name: shared
        translation_key: imdb_popular
      - name: arr
      - name: custom

  IMDb Top 250:
    variables:
      key: top
    template:
      - name: imdb_chart
        chart: top
      - name: shared
        translation_key: imdb_top
      - name: arr
      - name: custom

  IMDb Lowest Rated:
    variables:
      key: lowest
    imdb_chart: lowest_rated
    template:
      - name: shared
        allowed_libraries: movie
        translation_key: imdb_lowest
      - name: arr
      - name: custom
