##############################################################################
#                        Chart Separator Collections                         #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#   https://metamanager.wiki/en/latest/defaults/award/separator_chart.html   #
##############################################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "01"

translations:
  pmm: translations

collections:
  Chart Collections:
    template:
      - name: separator
        separator: chart
      - name: translation
        key_name: Chart
        translation_key: separator
