##############################################################################
#                        Tautulli Charts Collections                         #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#      https://metamanager.wiki/en/latest/defaults/chart/tautulli.html       #
##############################################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "01"
    image: chart/<<collection_name_encoded>>

translations:
  pmm: translations

templates:
  tautulli:
    default:
      list_days: 30
      list_size: 20
      list_days_<<key>>: <<list_days>>
      list_size_<<key>>: <<list_size>>
    tautulli_<<type>>:
      list_days: <<list_days_<<key>>>>
      list_size: <<list_size_<<key>>>>
      list_buffer: 20

collections:
  Plex Popular:
    variables:
      key: popular
    template:
      - name: tautulli
        type: popular
      - name: shared
      - name: custom
        template_variables:
          cache_builders: 0
      - name: translation
        translation_key: tautulli_popular

  Plex Watched:
    variables:
      key: watched
    template:
      - name: tautulli
        type: watched
      - name: shared
      - name: custom
        template_variables:
          cache_builders: 0
      - name: translation
        translation_key: tautulli_watched
