name: Docker Develop Release

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  docker-develop:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            "BRANCH_NAME=develop"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/plex-meta-manager:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.lxml
          build-args: |
            "BRANCH_NAME=develop"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/plex-meta-manager:lxml
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Send Discord Commit Notification
        uses: meisnate12/discord-notifications@master
        with:
          webhook_id: ${{ secrets.DEVELOP_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DEVELOP_WEBHOOK_TOKEN }}
          title: Plex Meta Manager Develop Commits
          message: "<@&954835263731949623> - An update to Plex Meta Manager has been published and is available to users of the **develop** branch.\n\nWe **strongly** recommend users who previously switched to the `nightly` branch to resolve any previous issues to now switch back to the `develop` branch now."
          commits: "true"
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/pmm.png

      - name: Discord Success Notification
        uses: meisnate12/discord-notifications@master
        if: success()
        with:
          webhook_id: ${{ secrets.BUILD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          title: "develop build: **Success**"
          url: https://github.com/meisnate12/Plex-Meta-Manager/actions/runs/${{ github.run_id }}
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/pmm.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/docker.png

      - name: Discord Failure Notification
        uses: meisnate12/discord-notifications@master
        if: failure()
        with:
          webhook_id: ${{ secrets.BUILD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          message: <@&1079153184007790652>
          title: "develop build: **Failure**"
          color: 0xe30c43
          url: https://github.com/meisnate12/Plex-Meta-Manager/actions/runs/${{ github.run_id }}
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/pmm.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/docker.png
