name: Docker Latest Release

on:
  push:
    branches: [ master ]

jobs:

  docker-latest:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/plex-meta-manager:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Lxml Version
        id: docker_build_lxml
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.lxml
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/plex-meta-manager:lxml
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Discord Success Notification
        uses: meisnate12/discord-notifications@master
        if: success()
        with:
          webhook_id: ${{ secrets.BUILD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          title: "latest build: **Success**"
          url: https://github.com/meisnate12/Plex-Meta-Manager/actions/runs/${{ github.run_id }}
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/.github/pmm.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/.github/docker.png

      - name: Discord Failure Notification
        uses: meisnate12/discord-notifications@master
        if: failure()
        with:
          webhook_id: ${{ secrets.BUILD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          message: <@&1079153184007790652>
          title: "latest build: **Failure**"
          color: 0xe30c43
          url: https://github.com/meisnate12/Plex-Meta-Manager/actions/runs/${{ github.run_id }}
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/.github/pmm.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/.github/docker.png