name: Release New Version

on:
  workflow_dispatch:

jobs:
  merge-master:
    runs-on: ubuntu-latest
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: nightly
          fetch-depth: 0

      - name: Create Release Commit and Synchronize Branches
        run: |
            value=$(cat VERSION)
            version="${value%-build*}"
            next_version="${{ vars.NEXT_VERSION }}"
            echo "CURRENT_VERSION: '${version}'"
            echo "NEXT_VERSION: '${next_version}'"
          
            if [[ "$version" == "$next_version" ]]; then
                echo "::error::NEXT_VERSION variable (${next_version}) must be incremented"
                exit 1
            fi
          
            echo "$next_version" > "VERSION"
          
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add VERSION
            git commit -m "Kometa Release ${next_version}"
            git push origin nightly
            git push origin refs/heads/nightly:refs/heads/develop
            git push origin refs/heads/nightly:refs/heads/main
